id: GistSource
key: GistSource
name: GistSource Plugin
version: 1.0
description: <__trans phrase="Eneble to Embed Gist Source notation">
author_name: maRk
author_link: http://labs.markdiary.com/
doc_link: http://www.markdiary.com/plugins/
blog_config_template: config.tmpl
l10n_lexicon:
    ja: l10n_ja.yaml
settings:
    doGistSource:
        Default: '1'
        Scope: blog
    addTypeAttribute:
        Default: '0'
        Scope: blog

tags:
    modifier:
        gistsource: $GistSource::GistSource::Tags::_hdlr_gist_source
